### ISSUE TITLE
Create UI mockup

### ISSUE THREAD

**Issue by G-Henderson** [SEPP-SSH/Shared-Groceries#19]
Create a mockup for the app's UI

**Comment by G-Henderson** [comment]
### 1st Mock Up Draft
Any thoughts from anyone?

![Screenshot_20241125-181014](https://github.com/user-attachments/assets/bcf81a2a-d7d8-43ef-ae5b-ca484f88886f)

**Comment by deserted-operative** [comment]
Looking great!

Was wondering whether you'd be able to add a label to indicate which supermarket the user is currently browsing.

Also wondered if you could add an "Offers" tab to the tab-bar at the top. 
Though this is a suggested feature of the selected EDR, I suggest we _don't_ propagate the tab with items, as being able to show just a subset of the grocery items from the supermarket isn't a significant technical challenge beyond simply showing _any_ grocery items, and as such, doesn't reflect a particularly high-risk aspect of the system, meaning it isn't a high priority feature for this prototype.
