### ISSUE TITLE
Write tests for database queries

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#25]
### Write tests for database queries
---
This includes:
- Planning out and documenting a proposed set of tests to provide us enough confidence to claim the database queries sufficiently effective.
- Implementing a series of tests that run in a GitHub Action to ensure that the database returns the expected data for each query.
- Ensuring that tests are combined in various orders to ensure that there are no unintended side-effects of each query.

**Comment by deserted-operative** [comment]
@Hasan24642 Would you be able to take a look at this one?

If you could design and document some tests _(see below)_ at `Documentation/SSH-Cloud/Unit Tests.md` in the `documentation/milestone-1` branch, and then implement them in the `unitTests` folder of the `feature/SSH-Cloud` branch, that'd be great :)

"Tests" -> unit tests that query/update the database and verify that the database is in the correct state after execution.

**Comment by Hasan24642** [comment]
> @Hasan24642 Would you be able to take a look at this one?
> 
> If you could design and document some tests _(see below)_ at `Documentation/SSH-Cloud/Unit Tests.md` in the `documentation/milestone-1` branch, and then implement them in the `unitTests` folder of the `feature/SSH-Cloud` branch, that'd be great :)
> 
> "Tests" -> unit tests that query/update the database and verify that the database is in the correct state after execution.

I will look into it.
