### ISSUE TITLE
Adding Supermarket APIs

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#27]
### Adding Supermarket APIs
---
This includes:
- Creating a hard-coded "Supermarket API" for SSH Cloud to access shopping item data.
- This should be where the SSH Cloud database gets it's placeholder/example data.

- Note again that this is hard-coded, rather than implemented using networking, to enable us to reach a viable prototype quicker, and limit scope.

**Comment by G-Henderson** [comment]
How about to simplify this we hard code the data from the various supermarkets into some kind of text file like a JSON or CSV instead of implementing a whole supermarket API as there aren't any readily available...

**Comment by deserted-operative** [comment]
This functionality has now been added to SSH Cloud in the form of JSON files that populate the database with initial data to simulate the API calls.
