### ISSUE TITLE
Testing SSH Cloud networking capabilities

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#28]
### Testing SSH Cloud networking capabilities
---
This includes:
- Writing automated tests that ensure SSH Cloud successfully accepts requests in its server capacity, and correctly processes the data included in said requests.

**Comment by deserted-operative** [comment]
@Hasan24642 

Could you take a look at this?

I've added a new branch called `Testing/SSH-Cloud-IntegrationTests`, where inside you'll find the `ClientFramework` project.

If you open this in IntelliJ, and then write some integration tests to check that the functions in the `Client` class in the project work as expected, so that we can be confident that the server is servicing requests correctly, that'd be amazing.

Bare in mind that these tests will be running on the live server, and thus need to be run in a specific order, where the actions of the previous tests will affect the state of the before the next test is run.

Thefore, I recommend that you put all of the tests in the same file, and _don't_ "clean" the database after each test, but rather factor in how you expect it to change after each subsequent test.
_(By placing them in the same test file, we can guarantee that they run sequentially)._

Note that at the moment you won't be able to run the tests unless you follow the "how to start the server" instructions from here: https://github.com/SEPP-SSH/Shared-Groceries/blob/1bcf2deb7fdd7878582a98f8a82b8f4b04fe02bb/Documentation/SSH%20App/How%20to%20run.md
_(I will be shortly adding a workflow to run these tests automatically, but it'd be great if you could start before I've got that working)._

And again, bare in mind that you'll need to close the server down and destroy its docker containers before re-running tests, as if you don't, data will persist in the docker container volumes between runs.

**Comment by Hasan24642** [comment]
Certainly!, thanks for the detailed instructions.
