### ISSUE TITLE
Choose an EDR

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#35]
### Choose an EDR
---
This involves:
- Choosing a team member's Engineering Design Review (EDR) to prototype.
- For the decision, the team should justify which EDR is chosen, and discuss any modifications that may need to be made to it for prototyping.
- Any changes agreed upon should be documented.

**Comment by deserted-operative** [comment]
As we discussed previously, we selected the attached Engineering Design Review (EDR) to prototype.

[Selected EDR](https://github.com/user-attachments/files/17917249/EDR.Submission.pdf)

**Comment by deserted-operative** [comment]
Looking at aspects of the EDR which should be simplified, altered, or omitted for the prototype, I propose:
-  Only populating a single category of items in the item selection view. This would include _not_ populating the "Offers" section. The reason behind this is as implementing support for a limited selection of items overcomes the largest challenge in the implementation, and adding further layers fo features on top of this doesn't add much in the way of reducing the risk of approving the project for full development.
- Not implementing the search functionality. For similar reasons as outlined above.
- Simulate/hard-code the items added to the group basket by other people in the shared house. i.e. The prototype being built should show how the system works from the perspective of one user - no multi-user functionality will be implemented. The rationale behind this is that it would require a lot of development time, and potentially cause confusion when demonstrating the prototype as to how the feature works, where it may be simpler to show only one part of the system moving at once, so to speak.
- Not developing the SSH Console Table implementation of the feature. This is because the EDR proposes that the SSH App and SSH Console Table use the same piece of software, only with layout alterations for the Console Table. Therefore, the viability of the system can be nearly entirely demonstrated by prototyping just one version.
- Not implementing the "order deadline" condition for placing an order. In the EDR, it's proposed that the order submission process is initiated at the order deadline. As this is a prototype, with no real access to supermarket APIs, I propose that for simplicity we use manual order submission.
- Omitting payment processing. Due to the complex and specialised nature of (responsibly) processing payments, I propose we simply simulate payment approval when an order acknowledgement is returned from the relevant server, rather than actually implementing any form of intelligible payment processing logic.
- Refactoring the milestones. I propose refactoring milestones into the following: Initial planning, Developing system foundations, Implementing network connectivity, Integrating the systems. The reason behind this change is to account for the much smaller number of people in the development team than was drawn upon in the selected EDR.
- Refactoring the teams. I propose that we initially split into two teams - one to work on SSH App, and another to work on SSH Cloud. When reaching Milestone 4: Integration, I propose the teams work in a less segmented fashion, on each others systems, to properly integrate them with each other. The reason for this change follows similar reasons as outlined above, with respect to development team size.

With respect to the refactored milestones, I've already added these into the GitHub repository, under the "Issues" tab. 

Any thoughts on the above? Any further changes? Let me know :)

**Comment by G-Henderson** [comment]
Yes, this seems like a good plan to me. Can I suggest that we do populate at least two categories of items as I think this would be beneficial to ensure that our system would work for adding the other categories later on? I also agree that the search functionality should be omitted initially as this adds a lot more complication to the front end.

**Comment by Hasan24642** [comment]
I fully agree with the proposed approach—it’s a practical and effective way to streamline the prototype development.
