### ISSUE TITLE
Finish Milestone 1 Documentation

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#47]
Finish the Milestone 1 documentation, located in the `documentation/milestone-1` branch, so that it can be merged onto `main` ASAP.

This includes:
- Adding the UI mockup and documenting decisions made its creation (suggested in the `Documentation/SSH App` directory)
- Adding the initial explanation for the choice of tech stack for SSH App (in the `Documentation/Initial Planning.md` file)

If you'd all have a review of what I've added so far, check you're happy with it, add in anything you think should be there, I'd be super grateful!

---

@G-Henderson  @parlatellioglu  @Hasan24642

**Comment by G-Henderson** [comment]
This has now been merged into the main branch.
