### ISSUE TITLE
Create returnHousemates function

### ISSUE THREAD

**Issue by G-Henderson** [SEPP-SSH/Shared-Groceries#49]
Server needs a function which returns a list of housemates given a specified `house_id`. This will be used to display the name of the housemate which added each item to the basket.

**Comment by G-Henderson** [comment]
Maybe you could return the list of housemates as part of the intial handshake, along with the `basket_id` and all those other things? What do you think?

**Comment by deserted-operative** [comment]
Will add as soon as possible :)

**Comment by deserted-operative** [comment]
Update - I've added the function to the `QueryServicer` class.

It just needs to be added to the documentation - this is a task I will complete once the Milestone 1 and Milestone 2 documentation branches have been finished and merged into `main`.

**Comment by deserted-operative** [comment]
Now documented.
