### ISSUE TITLE
Agree on a database schema

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#5]
### Agree on a database schema
---
**Before development** on either the SSH App or SSH Cloud products begins, the team should agree on the a schema for the database.

This _creates a specification_ for what data the front-end for the SSH App will draw on, and be expected to maintain and manipulate, as well as for what data SSH Cloud needs to host and provide accessors and mutators to.

This also _limits scope_, preventing the project from becoming too large.

**Comment by deserted-operative** [comment]
See attached, for your feedback, a draft of the proposed database schema for SSH Cloud. 

<img width="1035" alt="SSH Cloud Database Design" src="https://github.com/user-attachments/assets/95d03105-e61a-425e-b2ae-4e51c8f06760">

_(Constructed from the database schema outlined in the selected EDR)_

**Comment by deserted-operative** [comment]
Note - In the above diagram, I corrected an error from the selected EDR in the "BasketApproval" table.
In the selected EDR, both attributes of the composite primary key erroneously ommitted foreign key declarations.

**Comment by G-Henderson** [comment]
Nice! Looks great. Do we want to add a 'store_logo' attribute to the Store table?

**Comment by deserted-operative** [comment]
Absolutely!

<img width="1106" alt="SSH Cloud Database Design" src="https://github.com/user-attachments/assets/e62b0d74-efaa-496a-ae20-f736d01973b8">

**Comment by G-Henderson** [comment]
Awesome! I'd say we're ready to close this issue then - what do you think @parlatellioglu and @Hasan24642?

**Comment by Hasan24642** [comment]
I think it’s great. From the chosen EDR: “ If, at the order deadline, there are housemates that have not approved the basket, their items are removed, and the order proceeds with items added and approved by other housemates.”. Should we add “order_deadline” attribute to the BasketApproval table?

**Comment by Hasan24642** [comment]
I think it’s great and we’re ready to close this issue.

**Comment by parlatellioglu** [comment]
I agree, the design looks great.

**Comment by deserted-operative** [comment]
Whilst working on the Milestone 2 issue: https://github.com/SEPP-SSH/Shared-Groceries/issues/9, the database design proved problematic to implement. 

Particularly, the composite primary keys proved difficult to implement, and also made the data more difficult to track when serialising Java objects to the database.

Therefore, I'm proposing the following change to the SSH Cloud database schema:
<img width="1160" alt="SSH Cloud Database Design V3" src="https://github.com/user-attachments/assets/775f4e02-bcf7-4782-b5ce-06386b94d853">

I don't anticipate that this will greatly effect the SSH App development team, as the impact will be on the SSH Cloud end of servicing database requests.

Let me know how this looks :)

**Comment by G-Henderson** [comment]
Yes, this looks good to me. At what point is the item_quantity calculated?

**Comment by deserted-operative** [comment]
Whenever an item is added or removed, it sends the request to SSH Cloud which updates the values stored in the database.

On the SSH App end, can it just be tied to the quantity selected in the GUI?

_More detail on what I mean:_ https://github.com/SEPP-SSH/Shared-Groceries/issues/6#issuecomment-2512802258

**Comment by Hasan24642** [comment]
Looks good
