### ISSUE TITLE
Issue with return type of `returnBasketId` in `QueryServicer` in SSH Cloud

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#52]
As per the Milestone 1 documentation _(see `Documentation/SSH Cloud/Database Queries.md` in the project directory)_, the `returnBasketId` method of the `QueryServicer` class currently has the function prototype:

```java
public static Map<Integer, List<BasketItem>> returnBasketId(int houseId, int storeId){ ... }
```

In the process of implementing networking in Milestone 3, this particular return type has proven a challenge to deserialising the return object from the function.

Therefore, I propose replacing the function prototytpe with:

```java
public static ReturnedBasket returnBasketId(int houseId, int storeId){ ... }
```

where `ReturnedBasket` is a nested class within `QueryServicer` that wraps the `basketId` and `basketItems` values, like so:

```java
    public class ReturnedBasket{
        // attributes
        private Integer basketid;
        private List<BasketItem> basketItems;

        // constructor
        public ReturnedBasket(Integer basketid, List<BasketItem> basketItems){
            this.basketid = basketid;
            this.basketItems = basketItems;
        }

        // getters and setters...
}
```

@G-Henderson, @parlatellioglu thoughts on this would be appreciated :)

**Comment by G-Henderson** [comment]
I'm assuming this would require us to create the `ReturnedBasket` in the app also? If so, that's fine with me.

**Comment by deserted-operative** [comment]
I wouldn't think so - surely you'd just maintain the `basketId` and list of `basketItems` themselves - i.e. outside of the object wrapper?

**Comment by deserted-operative** [comment]
Clarification - from a networking point of view, the SSH App would have to extract the two values from the object, but wouldn't have to repackage them at any point to be sent back, as the data already exists in SSH Cloud's domain, and is updated as-required when items are added or removed.

**Comment by G-Henderson** [comment]
Okay cool. Sorry I misunderstood, how does this affect what we're doing?

**Comment by deserted-operative** [comment]
On your end, it should make it easer to pull the values out of the return object, as you'd have nice getters and setters instead of having to mess around with the `Map` object.

_But yes, it is a minor change..._

**Comment by G-Henderson** [comment]
I see, that sounds good then to me.

**Comment by deserted-operative** [comment]
I've now made the relevant changes to the SSH Cloud codebase - all that's left is to document the change, which I will do on the Milestone 3 documentation branch after the documentation branches for Milestone 1 and Milestone 2 have been completed and pulled into `main`.
