### ISSUE TITLE
Agree on a list of queries for the SSH Cloud database

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#6]
### Agree on a list of queries for the SSH Cloud database
---
Before any work begins on implementing dataflow routines between SSH App and SSH Cloud, the team should agree on a _specification_ of queries for how the database stored in SSH Cloud should be accessed and manipulated by clients.

**Comment by deserted-operative** [comment]
Building on our previous discussion on the networked actions which take place between SSH App and SSH Cloud, I'm proposing the following dataflows:

- An initial handshake between SSH App and SSH Cloud when SSH App starts up:
    - The app sends the `house_id` and `housemate_id` to SSH Cloud _(these values are hard-coded into the app for the scope of this prototype)_.
    - The server sends back a list of available stores.
    - The app chooses which store the order is for, and sends this over to SSH Cloud.
    - SSH Cloud returns a list of categories and items for that store, a `basket_id`, and a list of any items that are in this basket _(this list may be empty)_.
- Add item to basket:
    - The app sends the `basket_id`, `item_id`, `housemate_id` and quantity of items to add to SSH Cloud.
    - SSH Cloud handles the addition of the item to the basket, and sends back acknowledgement of the insertion.
- Remove an item from the basket:
    - The app sends the `basket_id`, `item_id`, `housemate_id` and quantity of items to remove to SSH Cloud.
    - SSH Cloud handles the removal of items from the basket, and sends back acknowledgement of the removal.
- Submit basket for order:
    - The app sends the `basket_id` to SSH Cloud.
    - SSH Cloud handles order submission _(which will be simulated for the scope of this prototype)_.
    - SSH Cloud sends back confirmation of the order placement.

Any thoughts?

**Comment by deserted-operative** [comment]
To go with this, I've drawn up some (very) rough pseudocode to show what (I propose) would happen in SSH Cloud upon receipt of these requests.

Of course, the arguments to each of these functions would be supplied by SSH App when requiring one of these functions to be executed.

```
func returnStores(house_id, housemate_id){
    // authentication step
    does house for supplied house_id exist?

    does housemate_id have a corresponding record with the house_id supplied? (meaning that they're in the same house)

    if above fails, return failure message, else: continue execution

    // return list of stores
    lookup all stores from database
    
    parse them to a list of java objects

    return the list of objects to the app
}


func returnCategories(store_id){
    lookup all categories in the database with the store_id supplied

    parse them into a list of java objects

    return the list of objects to the app
}


func returnBasketId(house_id, housemate_id, store_id){
    look for basket entry in the basket table of the database corresponding to the values provided

    if a basket exists, fetch the list of basket items, and return that list and the basket_id

    if the basket doesn't exist, make a new basket entry in the database, and return the basket_id
}


func addToBasket(basket_id, item_id, housemate_id, quantity){
    run checks on the quantity to check it's strictly greater than zero
    return error message if it's less than or equal to zero

    lookup whether item_id already has a record in the basket
    if it does{
        lookup who added the item
        if the housemate matches the housemate_id passed in{
            add quantity to the quantity already in the database
            return success message
        }
        else{
            add a new record, as this is a different housemate
            return success message
        }
    }
    else{
        add a new record
        return success message
    }
}


func removeFromBasket(basket_id, item_id, housemate_id, quantity){
    lookup whether item_id already has a record in the basket
    if it does{
        lookup who added the item
        if the housemate matches the housemate_id passed in{
            check whether the quantity supplied is greater than the number already in the database

            if it is, return error message, else: continue execution

            check whether the quantity supplied is equal to the number already in the database

            if it is, delete the record from the table and return success message, else: continue execution

            if execution has reached this point, update the database record with the reduced quantity (ie. quantity in database minus quantity supplied)

            return success message
        }
        else{
            return error message that housemate cannot remove other housemates' items
        }
    }
    else{
        return error message that item needs to be in basket to be removed
    }
}


func submitOrder(basket_id){
    return hardcoded approval acknowledgement of order
}

```

**Comment by G-Henderson** [comment]
Can I suggest that we also add another function called returnQuantity which returns the quantity for an item in the basket as it appears this will have been calculated at the time an item is added to the basket.

**Comment by G-Henderson** [comment]
Also can the server send the basket IDs for all the stores during the initial handshake?

**Comment by deserted-operative** [comment]
> Can I suggest that we also add another function called returnQuantity which returns the quantity for an item in the basket as it appears this will have been calculated at the time an item is added to the basket.

When would `returnQuantity` be called?

**Comment by deserted-operative** [comment]
> Also can the server send the basket IDs for all the stores during the initial handshake?

The challenge with that is that the baskets would have to exist for every store, even in the case where the users aren't placing orders with that supermarket.

Can still do this though if it simplifies things on the App side.

**Comment by G-Henderson** [comment]
> > Also can the server send the basket IDs for all the stores during the initial handshake?
> 
> The challenge with that is that the baskets would have to exist for every store, even in the case where the users aren't placing orders with that supermarket.
> 
> Can still do this though if it simplifies things on the App side.

Oh okay yes, would it be easier to get the basket items from the houseID and storeID? Instead of the app ever sending a basket ID.

**Comment by G-Henderson** [comment]
> > Can I suggest that we also add another function called returnQuantity which returns the quantity for an item in the basket as it appears this will have been calculated at the time an item is added to the basket.
> 
> When would `returnQuantity` be called?

When the app displays the quantity of each item on the basket screen. Also needs to know the quantity so that it can send the quantity +/- 1 when the user presses the +/- button on the basket screen.

**Comment by deserted-operative** [comment]
> > > Also can the server send the basket IDs for all the stores during the initial handshake?
> > 
> > 
> > The challenge with that is that the baskets would have to exist for every store, even in the case where the users aren't placing orders with that supermarket.
> > Can still do this though if it simplifies things on the App side.
> 
> Oh okay yes, would it be easier to get the basket items from the houseID and storeID? Instead of the app ever sending a basket ID.

Either way works fine :)

---

> When the app displays the quantity of each item on the basket screen. Also needs to know the quantity so that it can send the quantity +/- 1 when the user presses the +/- button on the basket screen.

Ah, what I wrote earlier is a little ambiguous.
In the initial handshake, the server sends back a `basket_id` and a list of `BasketItem`'s that are already in the basket. Each `BasketItem` object has an `item_quantity` attribute which you can use to populate the initial quantities of the items in the basket GUI.

**Comment by Hasan24642** [comment]
I think that covers everything for our prototype

**Comment by G-Henderson** [comment]
> > > > Also can the server send the basket IDs for all the stores during the initial handshake?
> > > 
> > > 
> > > The challenge with that is that the baskets would have to exist for every store, even in the case where the users aren't placing orders with that supermarket.
> > > Can still do this though if it simplifies things on the App side.
> > 
> > 
> > Oh okay yes, would it be easier to get the basket items from the houseID and storeID? Instead of the app ever sending a basket ID.
> 
> Either way works fine :)
> 
> > When the app displays the quantity of each item on the basket screen. Also needs to know the quantity so that it can send the quantity +/- 1 when the user presses the +/- button on the basket screen.
> 
> Ah, what I wrote earlier is a little ambiguous. In the initial handshake, the server sends back a `basket_id` and a list of `BasketItem`'s that are already in the basket. Each `BasketItem` object has an `item_quantity` attribute which you can use to populate the initial quantities of the items in the basket GUI.

Okay cool, I think we use houseID and storeID then as long as that doesn't add too much complication to your end. As for the item_quantity - this sounds good to me.
