### ISSUE TITLE
Document reasons for database queries

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#69]
@Hasan24642 Could you please go through the documentation at: `Documentation/SSH Cloud/Database Queries.md` and add in the explanations for why you identified the database actions as necesary, at the following lines in the file:
- Line 273
- Line 281
- Line 282
- Line 288
- Line 290
- Line 296
- Line 297
- Line 299
- Line 307
- Line 308
- Line 315
- Line 316

**Comment by Hasan24642** [comment]
Done. I deleted the methods, their unit tests and updated both documentation files (tests.md and Queries.md) - except for deleteById for the BasketItem.
