### ISSUE TITLE
Add missing unit tests

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#70]
@Hasan24642 Could you please add unit tests to the following handlers for the following database actions:
- `BasketHandler` - the `getBasketItemById` method needs uncommenting and fixing to run correctly (or the server logic needs updating if the test has identified something that isn't working as expected).
- `CategoryHandler` - the `getByStoreId` method (pertaining to categories) from the database queries list currently isn't being tested in this set of unit tests, and should be.
- `ItemHandler` - the `getByStoreId` method (pertaining to items) from the database queries list currently isn't being tested in this set of unit tests, and should be.

Could you also be sure to document that these unit tests have been added in the corresponding sections of the tables in the `Documentation/SSH Cloud/Database Queries.md` file after you've worked on them.

**Comment by Hasan24642** [comment]
Done.
