### ISSUE TITLE
Add parameters to SSH Cloud Unit Tests

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#71]
@Hasan24642 In the `Documentation/SSH Cloud/tests.md` file, the function prototypes for the tests you've added don't contain the parameters that would be expected.

I was wondering if you could add them?

Furthermore, would you please also be able to remove the tests that have been removed from the project?

**Comment by G-Henderson** [comment]
Completed by @Harvlovescactus
