### ISSUE TITLE
Implement the database

### ISSUE THREAD

**Issue by deserted-operative** [SEPP-SSH/Shared-Groceries#9]
### Implement the database
---
This includes:
- Creating all of the tables of the agreed database schema
- Ensuring all relations between tables are properly implemented, as per the design
- Ensuring that the database is normalised to third normal form (3NF)
- Populating all the tables with placeholder/example data that can be used for testing
- Linking the database to the Java framework that handles SSH Cloud logic

**Comment by G-Henderson** [comment]
This has been done now right?
